services:
  inference-gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.gateway
    image: dli-gateway:local
    container_name: inference-gateway
    ports:
      - "8000:8000"
    environment:
      STAGE_MAP_PATH: /app/configs/stage_map.yaml
      FIRST_STAGE_URL: http://inference-stage-1:8000/forward
    depends_on:
      - inference-stage-1

  inference-stage-1:
    build:
      context: .
      dockerfile: docker/Dockerfile.stage
    image: dli-stage:local
    container_name: inference-stage-1
    environment:
      STAGE_ID: "1"
      DLI_STAGE_RUNTIME: python-pytorch-legacy
      STAGE_MAP_PATH: /app/configs/stage_map.yaml
      NEXT_STAGE_URL: http://inference-stage-2:8000/forward

  inference-stage-2:
    image: dli-stage:local
    container_name: inference-stage-2
    environment:
      STAGE_ID: "2"
      DLI_STAGE_RUNTIME: python-pytorch-legacy
      STAGE_MAP_PATH: /app/configs/stage_map.yaml
      NEXT_STAGE_URL: http://inference-stage-3:8000/forward
    depends_on:
      - inference-stage-1

  inference-stage-3:
    image: dli-stage:local
    container_name: inference-stage-3
    environment:
      STAGE_ID: "3"
      DLI_STAGE_RUNTIME: python-pytorch-legacy
      STAGE_MAP_PATH: /app/configs/stage_map.yaml
      NEXT_STAGE_URL: http://inference-stage-4:8000/forward
    depends_on:
      - inference-stage-2

  inference-stage-4:
    image: dli-stage:local
    container_name: inference-stage-4
    environment:
      STAGE_ID: "4"
      DLI_STAGE_RUNTIME: python-pytorch-legacy
      STAGE_MAP_PATH: /app/configs/stage_map.yaml
      NEXT_STAGE_URL: ""
    depends_on:
      - inference-stage-3
