apiVersion: v1
kind: Service
metadata:
  name: inference-stage-4
  namespace: inference
spec:
  selector:
    app: inference-stage-4
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
