apiVersion: v1
kind: ConfigMap
metadata:
  name: dli-native-config
  namespace: inference
data:
  STAGE_MAP_PATH: "/app/configs/stage_map.yaml"

  HF_NATIVE_STAGE_REPO: "mipeda150/dli-tinyllama-native-gguf-4stage"
  HF_NATIVE_STAGE_REVISION: "main"

  HF_NATIVE_FULL_GGUF_REPO: "mipeda150/dli-tinyllama-native-gguf-4stage"
  HF_NATIVE_FULL_GGUF_REVISION: "main"
  HF_NATIVE_FULL_GGUF_FILE: "tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf"

  stage_map.yaml: |
    model_name: TinyLlama/TinyLlama-1.1B-Chat-v1.0
    num_layers: 22

    inference_gateway:
      service_name: inference-native-gateway
      port: 8000
      first_stage_url: http://inference-native-stage-1:8000/forward-binary

    inference_stages:
    - stage_id: 1
      partition_id: partition-1
      service_name: inference-native-stage-1
      physical_node: pinode7
      partition_file: /app/models/stage_1.pt
      native_partition_file: /app/models/partition-1.dli.gguf
      backend: llama
      components:
        embedding: true
        layers:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        norm: false
        lm_head: false
      next_stage_url: http://inference-native-stage-2:8000/forward-binary

    - stage_id: 2
      partition_id: partition-2
      service_name: inference-native-stage-2
      physical_node: pinode8
      partition_file: /app/models/stage_2.pt
      native_partition_file: /app/models/partition-2.dli.gguf
      backend: llama
      components:
        embedding: false
        layers:
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        norm: false
        lm_head: false
      next_stage_url: http://inference-native-stage-3:8000/forward-binary

    - stage_id: 3
      partition_id: partition-3
      service_name: inference-native-stage-3
      physical_node: pinode9
      partition_file: /app/models/stage_3.pt
      native_partition_file: /app/models/partition-3.dli.gguf
      backend: llama
      components:
        embedding: false
        layers:
        - 12
        - 13
        - 14
        - 15
        - 16
        norm: false
        lm_head: false
      next_stage_url: http://inference-native-stage-4:8000/forward-binary

    - stage_id: 4
      partition_id: partition-4
      service_name: inference-native-stage-4
      physical_node: pinode10
      partition_file: /app/models/stage_4.pt
      native_partition_file: /app/models/partition-4.dli.gguf
      backend: llama
      components:
        embedding: false
        layers:
        - 17
        - 18
        - 19
        - 20
        - 21
        norm: true
        lm_head: true
      next_stage_url: null

    topology:
      probe_timeout_seconds: 0.25
      route_candidates:
        "1":
        - http://inference-native-stage-2:8000/forward-binary
        "2":
        - http://inference-native-stage-3:8000/forward-binary
        "3":
        - http://inference-native-stage-4:8000/forward-binary