model_name: TinyLlama/TinyLlama-1.1B-Chat-v1.0
num_layers: 22
inference_gateway:
  service_name: inference-gateway
  port: 8000
  first_stage_url: http://inference-stage-1:8000/forward
inference_stages:
- stage_id: 1
  service_name: inference-stage-1
  physical_node: pinode7
  partition_file: /app/models/stage_1.pt
  components:
    embedding: true
    layers:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    norm: false
    lm_head: false
  next_stage_url: http://inference-stage-2:8000/forward
- stage_id: 2
  service_name: inference-stage-2
  physical_node: pinode8
  partition_file: /app/models/stage_2.pt
  components:
    embedding: false
    layers:
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    norm: false
    lm_head: false
  next_stage_url: http://inference-stage-3:8000/forward
- stage_id: 3
  service_name: inference-stage-3
  physical_node: pinode9
  partition_file: /app/models/stage_3.pt
  components:
    embedding: false
    layers:
    - 12
    - 13
    - 14
    - 15
    - 16
    norm: false
    lm_head: false
  next_stage_url: http://inference-stage-4:8000/forward
- stage_id: 4
  service_name: inference-stage-4
  physical_node: pinode10
  partition_file: /app/models/stage_4.pt
  components:
    embedding: false
    layers:
    - 17
    - 18
    - 19
    - 20
    - 21
    norm: true
    lm_head: true
  next_stage_url: null
